apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rabbitmq-deployment
  labels: 
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: url_image_rabbitmq:3-management
          ports: 
            - containerPort: 15672
